language: go
go:
  - "1.11"
env:
  - MONGODB_VERSION=3.4.18
matrix:
  include:
    - env: $MONGO_SETTINGS=--auth
      script:
        - go test ./... -tags=authentication
    - env: $MONGO_SETTINGS=
      script:
        - go test ./...
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db $MONGO_SETTINGS &
  - sleep 3
before_script:
  - mongorestore -h 127.0.0.1 --port 27017 -d data integration
  - mongo data --eval "db.getCollection('data').find({})"
